#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=train_mean
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=04:00:00
#SBATCH --output=;train_mean%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

# Your job starts in the directory where you call sbatch
cd $HOME/ATCS-practical
# Activate your environment
source activate ATCS
# Run your code
srun python train.py --epochs 50 --encoder_model mean --outputmodelname mean_model